server:
  port: 10000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shelter?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  sql:
    init:
      mode: always

api:
  earthquake:
    service-key: XANX2VH136BJA564
  chemical:
    service-key: 221O0952RC4482PC
  heat:
    service-key: KSYDEX371R6B5I07
  cold:
    service-key: 7TH2H36WY8VW30FM
  defense:
    service-key: HJWQIDG3KD670YGI